name: format check

on:
  push:
    branches:
      - mistress
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.17.0"
          rebar3-version: "3"

      - name: format check server
        run: gleam format --check src
        working-directory: server

      - name: format check client
        run: gleam format --check src
        working-directory: client

        - name: format check shared
        run: gleam format --check src
        working-directory: shared

